### ISSUE TITLE
ID: S17 As a user I want to see error messages more clearly, so that I can easily understand what invalid input I entered.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#113]
# Acceptance Criteria:

- [ ] The user can see an error message every time something goes.
- [x] The user can see an expressive message of what went wrong.

# Development tasks:
## Front-end:
- [x] sopra-fs22-group-02/client#58
- [x] sopra-fs22-group-02/client#59

## Back-end:
- [x] sopra-fs22-group-02/server#116
- [x] #141
- [x] sopra-fs22-group-02/server#117
- [x] sopra-fs22-group-02/server#118
