### ISSUE TITLE
ID: S18 As a user I want to be guided naturally through the application flow by adequate buttons, signifiers and constraints, so that my cognitive load is minimized. 

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#129]
# Acceptance Criteria:
- [x] An inexperienced user can sign up, create a place and an event in less than 2 minutes.
- [x] An inexperienced user can find and apply for a place in less than 90 seconds.
- [x] An inexperienced user can accept an applicant and successfully start a Q&A session in less than 90 seconds.

# Development tasks:
## Front-end:
- [x] sopra-fs22-group-02/client#70
- [x] sopra-fs22-group-02/client#71
- [x] sopra-fs22-group-02/client#72
- [x] sopra-fs22-group-02/client#73
- [x] sopra-fs22-group-02/client#74
