### ISSUE TITLE
ID: S2 As a registered user, I want to be able to login with my credentials (i.e. username and password that are both not empty words) so that I have access to the application.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#21]
# Acceptance Criteria:

- [ ] Upon successful user login, the home screen is shown.

- [ ] Upon failure, an error is displayed, and the user can try again. A login error can be that either username or password is wrong.

- [ ] Logged-in users can log out and log back into their registered profile.

# Development Tasks:
## Front-end:
- [x] sopra-fs22-group-02/client#4
- [x] sopra-fs22-group-02/client#5
- [x] sopra-fs22-group-02/client#6
## Back-end
- [x] #94
