### ISSUE TITLE
ID: S4 As a logged-in user, I want to edit my own user profile to set/update my personal information.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#23]
# Acceptance Criteria:

- [ ] By clicking on an edit button in the user-profile view, the user is able to change his/her username, password, biography etc. but not his/her UZH-email.

- [ ] A registered user can only change their own profile and not profiles of other users.

- [ ] After changing and saving the data, the user is redirected to the profile page and the new/changed data is displayed.

# Development Tasks:
## Front-end:
- [x] sopra-fs22-group-02/client#9
- [x] sopra-fs22-group-02/client#10
- [x] sopra-fs22-group-02/client#11
