### ISSUE TITLE
 ID: S5 As a logged-in user, I want to be able to see all events in a central weekly overview, so that I have a good insight into the upcoming week.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#24]
# Acceptance Criteria:

- [x] Every user can see their events for the upcoming week.

- [x] Events can be selected in the overview and more detail can be seen.

- [x] The events are labeled with a type {offered, applied, approved, expired} and their corresponding colour (applicant: yellow, provider: blue).

# Development Tasks (given that events can already be created):
## Front-end:
- [x] sopra-fs22-group-02/client#12
- [x] sopra-fs22-group-02/client#13

## Back-end:
- [x] sopra-fs22-group-02/server#53
- [x] sopra-fs22-group-02/server#54
- [x] #104
