### ISSUE TITLE
ID: S6 As a logged-in user (provider), I want to be able to create sleep events so that I can offer my place for other registered students to sleep.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#25]
# Acceptance Criteria:

- [x] The provider is able to add information date and time for the sleep event.

- [x] The provider is able to remove the event (once the event is over it’s not shown anymore).

# Development Tasks:
## Back-end:
- [x] sopra-fs22-group-02/server#55
- [x] sopra-fs22-group-02/server#57
- [x] sopra-fs22-group-02/server#58
- [x] sopra-fs22-group-02/server#101
- [x] sopra-fs22-group-02/client#60
## Front-end:
- [x] sopra-fs22-group-02/client#14
- [x] sopra-fs22-group-02/client#15
- [x] sopra-fs22-group-02/client#52
- [x] sopra-fs22-group-02/client#85
