### ISSUE TITLE
ID: S7 As a logged-in user, I want to inspect a sleep event’s profile page so that I can get detailed information about it.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#26]
# Acceptance Criteria:

- [ ] By clicking on a sleep event in the overview (list), the user is redirected to the sleep event's profile page.

- [ ] The page contains information about the area, the provider, date and time and a picture of the place.

- [ ] By clicking on the provider, the user is redirected to the provider’s user profile.

# Development tasks:
## Back-end:
- [x] sopra-fs22-group-02/server#61

## Front-end:
- [x] sopra-fs22-group-02/client#16
- [x] sopra-fs22-group-02/client#17
