### ISSUE TITLE
ID: S8 As a logged-in user (provider), I want to edit my sleep event's profile to set/update information.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#27]
# Acceptance Criteria:

- [ ] By clicking on an edit button in the sleep event profile, the user is able to change the date, time, area and state.

- [ ] A registered user can only modify sleep events where he/she is the provider.

- [ ] After changing and saving the data, the user is redirected to the sleep event’s profile page and the new/changed data is displayed.

# Development tasks:
## Front-end:
- [x] sopra-fs22-group-02/client#18
- [x] sopra-fs22-group-02/client#34

## Back-end:
- [x] sopra-fs22-group-02/server#66
