### ISSUE TITLE
ID: S9 As a logged-in user, I want to be able to filter sleep events offered by other registered students, so that I can have an overview of all events.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#28]
# Acceptance Criteria:

- [x] The user is able to filter sleep places by rough location (closest campus: Zentrum/Oerlikon/Hoenggerberg/Irchel).

# Development tasks:
## Front-end:

- [x] sopra-fs22-group-02/client#20
- [x] sopra-fs22-group-02/client#53
- [x] sopra-fs22-group-02/client#54

## Back-end:

- [x] sopra-fs22-group-02/server#69
