### ISSUE TITLE
ID: S11 As a logged-in user (provider), I want to be able to decide which applicant I want to accept for the sleep event.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#30]
# Acceptance Criteria:

- [x] After the applicant gets accepted by the provider, this event is labeled as "approved" for the applicant and the provider.
- [x] After an applicant gets accepted, the event doesn't show up anymore for ather users.

- [x] The provider can see all the applicants for an event in a list and then can accept one of them.
- [x] When an applicant is accepted, he/she is notified.

# Development tasks:
## Front-end:

- [x] sopra-fs22-group-02/client#22
- [x] sopra-fs22-group-02/client#23
- [x] sopra-fs22-group-02/client#24
- [x] sopra-fs22-group-02/client#61

## Back-end:

- [x] sopra-fs22-group-02/server#75
- [x] sopra-fs22-group-02/server#76
