### ISSUE TITLE
ID: S13 As a logged-in user (applicant or provider), after the applicant  is approved both users can start a Q&A session, so that they can get certain information. (e.g. ask whether the provider has bed sheets)

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#32]
# Acceptance Criteria:

- [x] The applicant can choose from a list of possible questions to ask the provider.

- [x] The provider can choose from a list of possible questions to ask the applicant.

- [x] Both can answer with Yes, No or Skip.

# Development tasks:
## Front-end:

- [x] sopra-fs22-group-02/client#25
- [x] sopra-fs22-group-02/client#26
- [x] sopra-fs22-group-02/client#55
- [x] sopra-fs22-group-02/client#56
- [x] sopra-fs22-group-02/client#57

## Back-end:

- [x] sopra-fs22-group-02/server#81
