### ISSUE TITLE
ID: S15 As a logged-in user, I want to see all the notifications I get, so that I’m always up to date concerning my current sleep events.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#34]
# Acceptance Criteria:
- [x] The user can see the notifications on the home screen.

- [x] By clicking on a notification the user is redirected to the corresponding page.

# Development tasks:
## Front-end:

- [x] sopra-fs22-group-02/client#28
- [x] sopra-fs22-group-02/client#29
- [x] sopra-fs22-group-02/client#30
- [x] sopra-fs22-group-02/client#31
- [x] sopra-fs22-group-02/client#62

## Back-end:
- [x] sopra-fs22-group-02/server#89
- [x] sopra-fs22-group-02/server#103
