### ISSUE TITLE
ID: S16 As a logged-in user (provider), I want to be able to create a page for my place, so that I can offer sleep events.

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/server#35]
# Acceptance Criteria:

- [x] The user can provide details: name, picture, description, nearest campus
- [ ] The user can cllick on "my place" on the home screen to get to the place's profile page.
- [ ] The user is able to  edit and delete the profile. 

# Development tasks:
## Front-end:

- [x] sopra-fs22-group-02/client#32
- [x] sopra-fs22-group-02/client#33

## Back-end:

- [x] sopra-fs22-group-02/server#92
- [ ] sopra-fs22-group-02/server#93
